language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - pecl install uopz
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.xml
  - ./vendor/bin/phpstan analyse --level=4 src/

after_success:
  - bash <(curl -s https://codecov.io/bash)
